### ISSUE TITLE
想问下为什么登录时命中了Redis缓存，又去MySql查呢

### ISSUE THREAD

**Issue by SyncdevWu** [StellarisW/gohu#3]

**Comment by StellarisW** [comment]
少写了这一行代码
https://github.com/StellarisW/gohu/blob/master/app/service/user/rpc/crud/internal/logic/loginlogic.go#L91

另外这个是我很久之前的项目了，有些不规范和疏漏的地方一直没时间改，参考一下就行了，
比如：
- 缓存可以放在api层查找比较好，
- 校验参数的话应该只用在api层校验就行了，https://github.com/StellarisW/gohu/blob/master/app/service/user/rpc/crud/internal/logic/loginlogic.go#L49 这段代码就不应该写
- `logger.Debugf("send message: %v", res.String())`这之类的代码放在 rpc/xxx/internal/server/xxxserver.go这个文件里，就不用在logic文件里写冗余的代码了

另外欢迎提交pr
